kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-kubernetes-linux-amd64
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      repo: briandowns/kubernetes-image-building
      tag: "${DRONE_TAG}-linux-amd64"
    when:
      instance:
        - drone-publish.rancher.io
      event:
        - tag
