---
kind: pipeline
name: linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/hardened-build-base:v1.16.6b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - make image-build

- name: scan
  image: rancher/hardened-build-base:v1.16.6b7
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - TAG=${DRONE_TAG} make image-scan
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

- name: publish
  image: rancher/hardened-build-base:v1.16.6b7
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
      - tag
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: linux-s390x
platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
- name: build
  image: rancher/hardened-build-base:v1.16.9b7
  failure: ignore
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - make image-build

- name: publish
  image: rancher/hardened-build-base:v1.16.9b7
  failure: ignore
  commands:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make DRONE_TAG=${DRONE_TAG} image-push
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  volumes:
    - name: docker
      path: /var/run/docker.sock
  when:
    event:
    - tag
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: manifest
platform:
  os: linux
  arch: amd64
steps:
- name: push
  image: plugins/manifest:1.2.3
  settings:
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    spec: manifest.tmpl
    ignore_missing: true
  when:
    event:
    - tag
depends_on:
  - linux-amd64
  - linux-s390x
...
