on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read
  security-events: write # upload Sarif results

name: Build
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"

    - name: Set the GO_IMAGE value
      id: get-GO_IMAGE
      run: |
        echo GO_IMAGE=rancher/hardened-build-base:$(./scripts/golang-version.sh ${{ env.TAG }}) >> "$GITHUB_ENV"

    - name: Build container image
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: .
        push: false
        tags: rancher/hardened-kubernetes:${{ env.TAG }}-amd64
        file: Dockerfile
        build-args: |
          TAG=${{ env.TAG }}
          GO_IMAGE=${{ env.GO_IMAGE }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        image-ref: rancher/hardened-kubernetes:${{ env.TAG }}-amd64
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

    - name: Set up Docker Buildx
      id: builder
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"

    - name: Set the GO_IMAGE value
      id: get-GO_IMAGE
      run: |
        echo GO_IMAGE=rancher/hardened-build-base:$(./scripts/golang-version.sh ${{ env.TAG }}) >> "$GITHUB_ENV"

    - name: Build container image
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: .
        push: false
        tags: rancher/hardened-kubernetes:${{ env.TAG }}-arm64
        file: Dockerfile
        outputs: type=docker
        platforms: linux/arm64
        build-args: |
          TAG=${{ env.TAG }}
          GO_IMAGE=${{ env.GO_IMAGE }}

