on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read
  security-events: write # upload Sarif results

name: Build
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"

    - name: Set the GO_IMAGE value
      id: get-GO_IMAGE
      run: |
        echo GO_IMAGE=rancher/hardened-build-base:$(./scripts/golang-version.sh ${{ env.TAG }}) >> "$GITHUB_ENV"

    - name: Build container image
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: .
        push: false
        tags: rancher/hardened-kubernetes:${{ env.TAG }}-amd64
        file: Dockerfile
        build-args: |
          TAG=${{ env.TAG }}
          GO_IMAGE=${{ env.GO_IMAGE }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      with:
        image-ref: rancher/hardened-kubernetes:${{ env.TAG }}-amd64
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

    - name: Set up Docker Buildx
      id: builder
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

    - name: Set the TAG value
      id: get-TAG
      run: |
        echo "$(make -s log | grep TAG)" >> "$GITHUB_ENV"

    - name: Set the GO_IMAGE value
      id: get-GO_IMAGE
      run: |
        echo GO_IMAGE=rancher/hardened-build-base:$(./scripts/golang-version.sh ${{ env.TAG }}) >> "$GITHUB_ENV"

    - name: Build container image
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: .
        push: false
        tags: rancher/hardened-kubernetes:${{ env.TAG }}-arm64
        file: Dockerfile
        outputs: type=docker
        platforms: linux/arm64
        build-args: |
          TAG=${{ env.TAG }}
          GO_IMAGE=${{ env.GO_IMAGE }}

